# Generated by Django 4.2.7 on 2023-12-19 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0002_alter_producto_categoria_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
